---
- name: ubuntu | ensuring Ubuntu universe repo is enabled ({{ ansible_distribution_version }} >= 16.04)
  apt_repository:
    repo: "deb http://us.archive.ubuntu.com/ubuntu {{ ansible_distribution_release|lower }} universe"
    state: present
  when: ansible_distribution_version >= '16.04'
  become: yes

- name: update apt cache
  apt: update_cache=yes
  changed_when: false
  become: yes

- name: Install performance tools
  apt: pkg={{ item }} state=present
  with_items:
   - htop
   - stress
   - sysdig
  become: yes

- name: Install io tools
  apt: pkg={{ item }} state=present
  with_items:
   - iotop
   - lsof
   - sysstat
  become: yes

- name: Install http tools
  apt: pkg={{ item }} state=present
  with_items:
   - curl
   - wget
   - jq
   - httpie
  become: yes

- name: Install network tools
  apt: pkg={{ item }} state=present
  with_items:
   - net-tools
   - tcpdump
   - dnsutils
   - nethogs
   - slurm
   - nload
   - bmon
   - tcptrack
   - speedometer
   - ifstat
   - iftop
  become: yes

- name: Install s3cmd for backup s3
  apt: pkg={{ item }} state=present
  with_items:
   - s3cmd
  become: yes

- name: Install utils packages
  apt: pkg={{ item }} state=present
  with_items:
   - multitail
   - tree
  become: yes
